### ISSUE TITLE
Reoccuring events

### ISSUE THREAD

**Issue by olymk2** [GetTogetherComm/GetTogether#63] opened 2018-04-04 07:41 UTC
Need a feature to create events that happen weekly or monthly, currently you have to create the same event repeatedly.

Some kind of drop down perhaps that lets you choose the repeat frequency.

**Comment by craigmaloney** [comment] 2018-04-04 10:41
This is a duplicate of #40

**Comment by mhall119** [comment] 2018-04-04 14:12
It is indeed.

**Closed by mhall119** 2018-04-04 14:12 UTC
